name: Process Markdown

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install any dependencies if needed
        # pip install -r requirements.txt

    - name: Run script
      run: |
        python your_script_name.py
      # Ensure your script is named correctly and located in the root directory

    - name: Commit changes
      run: |
        git config --local user.email "sushantbagul074@gmail.com"
        git config --local user.name "Sushant1209"
        git add submissions.md
        git commit -m "Update submissions.md with processed links"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
