name: Process and Update Submissions

on:
  push:
    branches:
      - master

permissions:
  contents: write
  workflows: read

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run submission processing script
      run: |
        python submission.py

    - name: Configure Git
      run: |
        git config --local user.email "sushantbagul074@gmail.com"
        git config --local user.name "Sushant"

    - name: Commit changes
      run: |
        git add submissions.md
        git commit -m "Update submissions.md with processed links" || echo "No changes to commit"
        git push
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
